# Generated by Django 5.1 on 2024-09-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_is_verified_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prn',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
