# Generated by Django 5.0.7 on 2024-08-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0002_questionai'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='QuestionAI',
        ),
    ]
