# Generated by Django 5.0.7 on 2024-08-25 12:35

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0004_rename_image_question_image_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('D:/code 2024/sem 5/ai/static/questions')), upload_to=''),
        ),
    ]
