# Generated by Django 5.0.7 on 2024-08-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0005_question_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
