# Generated by Django 5.0.7 on 2024-09-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0009_quiz_duration_quiz_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False')], default='MCQ', max_length=3),
        ),
    ]
