# Generated by Django 5.0.7 on 2024-09-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0012_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
