# Generated by Django 5.1.6 on 2025-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0014_alter_quizresult_options_remove_question_image_loc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_loc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
